### PR TITLE
Feature/driverkit

### PR DESCRIPTION
**Pull request by tekezo**

### CODE REVIEW

**Comment by lbibass** [comment]
Just a note, on beta 6 it still doesn't seem to work. The log says, "[2020-09-09 12:18:12.872] [info] [grabber] virtual_hid_device_service_client_ connect_failed: Connection refused". Any ideas on what is going on?

**Comment by lbibass** [comment]
I have already done that @babygau. It still does not work.

**Comment by tekezo** [comment]
@lbibass Could you show me the contents of `/var/log/karabiner/virtual_hid_device_service.log`?

**Comment by tekezo** [comment]
@lbibass 
I released new version (12.93.0) which fixed a bug. Please confirm it.
https://karabiner-elements.pqrs.org/docs/macos-big-sur/

**Comment by imagine** [comment]
Complex modifications
- Not working: Double tap and hold left_command to become left_control
  - EventViewer shows the correct remap, but Safari doesn't switch tabs for example
- Not working: Change caps_lock to command+control+option+shift
  - EventView shows the correct remap, but QuickSilver only gets command+option+shift, missing control modifier.
- Working: option + f12 to volume_increment

**Comment by tekezo** [comment]
@imagine Thank you for feedback!
It seems Karabiner-Elements works well.
EventViewer shows the result of Karabiner-Elements, but the input events might be changed by other apps after Karabiner-Elements changes them.

Did you change control key to option by other apps such as hidutil?

**Comment by imagine** [comment]
Yes! I had a lingering com.local.KeyRemapping.plist LaunchAgent 🎆

**Comment by babygau** [comment]
to me, running shell command is not working. other keybindings is ok

**Pull request merged**
