### PR TITLE
add Consumer key for music player

### LINKED ISSUE #3453: one key not detectable on Microsoft Ergonomic Keyboard
I have [Microsoft Ergonomic Keyboard LXM-00001](https://www.microsoft.com/en/accessories/products/keyboards/microsoft-ergonomic-keyboard?activetab=pivot:overviewtab). There's only one key that's completely undetectable by the Event Viewer: the button between sound and player controls.

I wanted to debug what's going on with that key, but didn't quite figure out how to do it. Even if I run Xcode as root it still doesn't let me to attach to karabiner_observer process.

P.S. Also some keys just send shortcuts instead of being detected as separate keys (see details in https://github.com/pqrs-org/Karabiner-Elements/issues/2460#issuecomment-1510279674), but not sure if that's possible.

### PR DESCRIPTION
**Pull request by kambala-decapitator**
Complementing https://github.com/pqrs-org/cpp-hid/pull/1

fixes #3453

### CODE REVIEW

**Comment by kambala-decapitator** [comment]
should I maybe name the key differently? According to standard it's **AL Consumer Control Configuration Tool**:

> Used to associate generic controls with a sepcific consumer device or software player to receive the control input, regardless of user focus. For example, a set of Transport Controls could be associated with a DVD-ROM player that would receive the Mute input even when it does not have the user focus.

**Comment by tekezo** [comment]
@kambala-decapitator 
Thank you for PR!

> should I maybe name the key differently? According to the [standard](https://www.usb.org/sites/default/files/hut1_5.pdf) it's AL Consumer Control Configuration Tool:

Yes, I have given this some thought.
There is another key, e.g. AL Audio Browser, so let me change 0x0183 name to `al_consumer_control_configuration`.
I'll merge this change by new PR.
https://github.com/pqrs-org/Karabiner-Elements/pull/3758

**Comment by kambala-decapitator** [comment]
@tekezo I completely agree, thanks a lot! Will close this PR.

**Comment by tekezo** [comment]
@kambala-decapitator `al_consumer_control_configuration` is available since Karabiner-Elements 14.13.12 (beta release).

Screenshot 2024-03-30 at 7 46 38

How to upgrade to the latest beta version:
Check for beta updates

**Comment by kambala-decapitator** [comment]
@tekezo thanks! In the beta version the key works and opens Music app, simple modifications also work. However, the event viewer doesn't report the button when it's pressed.

**Comment by kambala-decapitator** [comment]
> However, the event viewer doesn't report the button when it's pressed.

@tekezo FYI still the case in 14.99.3

**Pull request closed without merging**
