### PR TITLE
Added new app icon

### LINKED ISSUE #499: New Icon
I've designed a new icon for Karabiner. You're welcome to use it.

app
icon statusbar 2x

Zip with sketch file: 
[Archive.zip](https://github.com/tekezo/Karabiner-Elements/files/659754/Archive.zip)

### PR DESCRIPTION
**Pull request by bennypowers**
closes #499

### CODE REVIEW

**Comment by sn0wyfall** [comment]
Looks a bit too bright IMO. Maybe if it were a bit more subtle it would look really nice. Thoughts?

**Comment by carlsmith** [comment]
It's a much nicer logo, by far, but is a bit too bright. Can you not use something closer to the original Karabiner Purple? That would also make the white legend stand out more. It would also be good if the K was more like the original logotype.

**Comment by bennypowers** [comment]
Updated colour and logotype. there's also these for the statusbar I'm not sure where they go.

icon statusbar 44

icon statusbar 44 2x

icon statusbar

icon statusbar 2x





[tiffs.zip](https://github.com/tekezo/Karabiner-Elements/files/969587/tiffs.zip)

**Comment by carlsmith** [comment]
Nice one. It'd be good to see these used with the next release. It's cool that the logo looks like an iteration on the current one. People will recognise it more easily. 

A lot of Karabiner users are keyboard enthusiasts, so a keycap was a nice choice for a logo too.

**Comment by bennypowers** [comment]
should i bother rebasing, or should this just be closed?
#500 opened on Dec 19, 2016 by bennypowers

**Comment by hologerry** [comment]
No offense, just as far as the icons are concerned.
To be honest, I prefer the old version (current stable release), sorry.
We can vote for this.

**Comment by sn0wyfall** [comment]
Okay I'll be straight up honest—none of these icons look good, imo. Most macOS icons are really nicely made but these ones seem kind of... to simplistic. I don't mean offense to anyone and I'm not saying that I could make something better, but I wish there were better icons

**Pull request closed without merging**
