### PR TITLE
New icons proposal

### PR DESCRIPTION
**Pull request by Zabriskije**
Hi folks, this is a proposal to update the current icons to comply more with Big Sur, Monterey, and Ventura's visual styles.
Here you can see the current ones (on the left) and the proposed ones (on the right):

### CODE REVIEW

**Comment by Zabriskije** [comment]
Hey @tekezo,
What do you think? 👀

**Comment by tekezo** [comment]
Sorry for the delay.
I'm wondering if we can theme the icons since everyone has their own preferences for icons.
I would like to make it selective once we have that support.

**Comment by Zabriskije** [comment]
I can't help with that, but I've found this in Apple's documentation: [Configuring Your App to Use Alternate App Icons](https://developer.apple.com/documentation/xcode/configuring_your_app_to_use_alternate_app_icons)

Personal preferences aside, I think the current ones need a refresh. They don't meet the current standards in terms of visuals and use a dated style.

Hope that doesn't sound arrogant 😅 I've tried to rephrase it, but I haven't found any simpler words.

**Comment by tekezo** [comment]
Now, we can change the icon in the latest beta version (v14.11.9)
https://github.com/pqrs-org/Karabiner-Elements/pull/3451

**Pull request closed without merging**
